# Generated by Django 5.2.3 on 2025-07-29 13:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liebes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
