# Generated by Django 5.2.3 on 2025-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liebes', '0002_shoe_uploaded_at_alter_shoe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
